cars = ['bmw', 'audi', 'toyota', 'subaru']
print("\nHere is the list of cars")
print(cars)
print("\nHere is the list of sorted cars")
print(sorted(cars))
print("\nHere is the original list again")
print(cars)
print("\nHere's the list but backwards")
cars.reverse()
print(cars)
cars.sort()
print("\n Now we have it back in alphebetical order:")
print(cars)
print("\nI wonder how many cars are in this list?")
print(len(cars))