locations = ['prague', 'everest', 'seattle', 'kilimanjaro', 'paris']
print(locations)
print(sorted(locations))
print(locations)
print(sorted(locations, reverse=True))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)


applications = ['harvard', 'yale', 'princeton', 'cornell', 'dartmouth', 'rpi', 'georgia tech', 'williams', 'amherst', 'stanford']
print(len(applications))
print(sorted(applications, reverse=True))
print(sorted(applications))
print(applications)
applications.reverse()
print(applications)
applications.sort()
print(applications)
applications.sort(reverse=True)
print(applications)
oneless = applications.pop()
print(oneless)
print(applications)
applications.append('amherst')
print(applications)
applications.sort()
print(applications)
applications.insert(3,'usc')
print(applications)
applications.sort(reverse=True)
print(applications)